import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import ToastProvider from '@/components/providers/toaster-provider';

import { ruRU } from "@clerk/localizations";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ИОР Аловт',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <ClerkProvider localization={ruRU}>
      
      <html lang="ru">
        <body className={inter.className}>
          <ToastProvider />
          {children}
        </body>
        
      </html>
      
    </ClerkProvider>

  );
}